# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
