# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_letter', '0002_deliverytype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
